name: "SSH Run Docker Compose Command"
description: "SSH Run Docker Compose Command"
inputs:
  command:
    description: "Docker compose options"
    required: true
  remote-ssh-chain:
    description: "Remote ssh chain to remote server"
    required: true
  remote-path:
    description: "Remote: root path"
    required: true
  docker-registry:
    description: "Docker registry host (default: Docker Hub)"
    required: false
  docker-username:
    description: "Docker login: Username"
    required: false
  docker-token:
    description: "Docker login: Token"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Docker Login"
      if: ${{ inputs.docker-username && inputs.docker-token }}
      uses: draftm0de/github.scripts/.github/actions/ssh-docker-login@main
      with:
        remote-ssh-chain: ${{ inputs.remote-ssh-chain }}
        remote-path: ${{ inputs.remote-path }}
        docker-registry: ${{ inputs.docker-registry }}
        docker-username: ${{ inputs.docker-username }}
        docker-token: ${{ inputs.docker-token }}

    - name: "Run Docker Compose Command"
      shell: bash
      run: |
        echo "::group::Executing docker compose..."
        path="${{ inputs.remote-path }}"
        ssh_chain="${{ inputs.remote-ssh-chain }}"            
        command="${{ inputs.command }}"
        echo "✅ docker compose $command"
        echo "::notice::docker compose ${command}"

        ssh "${ssh_chain}" <<EOF
        cd "${path}"
        docker compose ${command}
        EOF

        echo "::endgroup::" 

    - name: "Post: Docker Logout"
      if: ${{ inputs.docker-username && inputs.docker-token }}
      shell: bash
      run: |
        docker logout "${{ inputs.docker-registry }}"
