name: "Build ssh connection"
description: "Build ssh connection"
inputs:
  remote-host:
    description: "Remote: host"
    required: true
  remote-port:
    description: "Remote: port"
    required: false
    default: "22"
  remote-user:
    description: "Remote: user"
    required: true
  remote-ssh-key:
    description: "Remote: ssh key"
    required: true

outputs:
  remote-server:
    description: "SSH server"
    value: ${{ steps.build.outputs.server }}
  remote-ssh-chain:
    description: "SSH chain to remote server"
    value: ${{ steps.build.outputs.chain }}

runs:
  using: "composite"
  steps:
    - name: "Build SSH Chain"
      id: build
      shell: bash
      run: |
        echo "::group::Building ssh chain"
        ssh_path="${HOME}/.ssh"
        ssh_key_file="${ssh_path}/id_rsa"
        server="${{ inputs.remote-host }}"
        port="${{ inputs.remote-port }}"           
        mkdir -p ${ssh_path}
        
        # store ssh-key on remote server
        echo "${{ inputs.remote-ssh-key }}" > "${ssh_key_file}"        
        chmod 600 ${ssh_key_file}
        echo "✅ created ssh key file"
        echo "::notice::created ssh key file"
        
        known_hosts_file="${ssh_path}/known_hosts"
        if [ "${port}" = "22" ]; then
          ssh-keyscan -H ${server} >> ${known_hosts_file}
        else
          ssh-keyscan -p ${port} -H ${server} >> ${known_hosts_file}
        fi
        echo "✅ remote server added to ~/.ssh/known_hosts"
        echo "::notice::remote server added to ~/.ssh/known_hosts"
        
        user="${{ inputs.remote-user }}"
        ssh_chain="${user}@${server}"
        if [ "${port}" != "22" ]; then
          ssh_chain="${ssh_chain}:${port}"
        fi
        echo "✅ ssh chain successfully prepared ($ssh_chain)"
        echo "::notice::ssh chain successfully prepared"

        echo "::endgroup::"        
        echo "server=$server" >> $GITHUB_OUTPUT        
        echo "chain=$ssh_chain" >> $GITHUB_OUTPUT                
